### ISSUE TITLE
Android developer wanted!

### ISSUE THREAD

**Issue by limo1996** [haroldadmin/lucilla#12]
Hi Kshitij,

Your GitHub profile caught me eye! We are searching for amazing Android developers and I think you can be the one! Would you have few minutes to jump on a call with me and talk about possible opportunities at ElevenLabs?

Kind regards,
Jakub

**Comment by haroldadmin** [comment]
Thank you for the opportunity @limo1996. Let's discuss over LinkedIn instead, I have sent you a connection request.
